### ISSUE TITLE
is this a error?

### ISSUE THREAD

**Issue by liamxg** [acegid/SARS-CoV-2_Manuscript_Supplemental_Data#2]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/46078579/218702616-9015e602-e7c0-4b6e-8e60-3ea83dbcab30.png">

**Comment by liamxg** [comment]
@acegid

**Comment by acegid** [comment]
That part of the code should have been commented or left out. It isn't supposed to be there

**Comment by liamxg** [comment]
@acegid thanks.
