### ISSUE TITLE
could you please upload the "Markov_jumps_EXPORT_bin_normalized_month.csv"" file?

### ISSUE THREAD

**Issue by liamxg** [acegid/SARS-CoV-2_Manuscript_Supplemental_Data#3]
and the "Markov_jumps_EXPORT_overall.csv" file and the "old_increase_in_travel.csv" file and so on. @EdythParker

**Comment by EdythParker** [comment]
Hey Liam -- the travel data is from a private company, so I can't release that publicly without their permission -- if you drop me an email at eparker@scripps.edu on what analyses you're particularly trying to replicate I can help you out!

**Comment by liamxg** [comment]
@EdythParker thanks,I will email to you.
